### ISSUE TITLE
Enhancement: Adding opacity to radio images to improve distinction

### ISSUE THREAD

**Issue by jetonr** [valendesigns/option-tree#234]
This is an enhancement and not a bug

``` css
.type-radio-image .option-tree-ui-radio-images img {
        opacity: 0.6;
}

.type-radio-image .option-tree-ui-radio-images img.option-tree-ui-radio-image-selected,
.type-radio-image .option-tree-ui-radio-images img:hover {
        opacity: 1;   
}
```

Result: 
![readio_images](https://f.cloud.github.com/assets/2385217/2005637/629ca420-86f3-11e3-9861-8d22c33ae9b1.png)
