### ISSUE TITLE
Bug: box-sizing on date picker

### ISSUE THREAD

**Issue by sparkdevelopment** [valendesigns/option-tree#237]
I've noticed that on the date picker in wip (a much needed feature btw) I need to explicitly set 

``` css
.ui-datepicker td span, .ui-datepicker td a {
   box-sizing: border-box;
}
```

 otherwise the calendar part of the picker spills outside of the calendar container as each date has an extra 10px of padding added to them.
